### PR TITLE
initial starter yaml

### PR DESCRIPTION
**Pull request by gecock**
removed secrets

Also playing around with plugins in the PR comments...

### CODE REVIEW

**Comment by kabynarow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/tseeorg/testops/pull/1#issuecomment-653172939" title="Approved">gecock</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kabynarow**
You can assign the PR to them by writing `/assign @kabynarow` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=tseeorg%2Ftestops).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/tseeorg/testops/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kabynarow** [comment]
@gecock: GitHub didn't allow me to assign the following users: me.

Note that only [tseeorg members](https://github.com/orgs/tseeorg/people), repo collaborators and people who have commented on this issue/PR can be assigned. Additionally, issues/PRs can only have 10 assignees at the same time.
For more information please see [the contributor guide](https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github)

<details>

In response to [this](https://github.com/tseeorg/testops/pull/1#issuecomment-653173172):

>/assign me


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kabynarow** [comment]
@gecock: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/tseeorg/testops/pull/1#issuecomment-653173748):

>/lgtm
>/approve


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kabynarow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/tseeorg/testops/pull/1#issuecomment-653173748" title="Approved">gecock</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kabynarow**
You can assign the PR to them by writing `/assign @kabynarow` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=tseeorg%2Ftestops).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/tseeorg/testops/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kabynarow** [comment]
@gecock: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/tseeorg/testops/pull/1#issuecomment-653175653):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kabynarow** [comment]
@gecock: I adopted my dog from a blacksmith. As soon as we got home he made a bolt for the door.

<details>

In response to [this](https://github.com/tseeorg/testops/pull/1#issuecomment-653179085):

>/joke


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by tseelbach — APPROVED** [review]

**Comment by kabynarow** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/tseeorg/testops/pull/1#issuecomment-653173748" title="Approved">gecock</a>*, *<a href="https://github.com/tseeorg/testops/pull/1#pullrequestreview-442035289" title="Approved">tseelbach</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=tseeorg%2Ftestops).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/tseeorg/testops/blob/master/OWNERS)~~ [tseelbach]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
